package com.github.gv2011.textconv.gui;

final class TextconvJFrame extends javax.swing.JFrame {

    /**
     * Creates new form TextconvJFrame
     */
    TextconvJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        vertSplit = new javax.swing.JSplitPane();
        textSplit = new javax.swing.JSplitPane();
        textInScroll = new javax.swing.JScrollPane();
        textIn = new javax.swing.JTextArea();
        textOutScroll = new javax.swing.JScrollPane();
        textOut = new javax.swing.JTextArea();
        logScroll = new javax.swing.JScrollPane();
        logArea = new javax.swing.JTextArea();
        menubar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolbar.setRollover(true);

        jButton1.setText("tool1");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(jButton1);

        jButton2.setText("tool2");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(jButton2);

        vertSplit.setDividerLocation(600);
        vertSplit.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        textSplit.setDividerLocation(580);

        textIn.setColumns(20);
        textIn.setFont(new java.awt.Font("Noto Mono", 0, 11)); // NOI18N
        textIn.setRows(5);
        textInScroll.setViewportView(textIn);

        textSplit.setLeftComponent(textInScroll);

        textOut.setColumns(20);
        textOut.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        textOut.setRows(5);
        textOut.setEnabled(false);
        textOutScroll.setViewportView(textOut);

        textSplit.setRightComponent(textOutScroll);

        vertSplit.setTopComponent(textSplit);

        logScroll.setPreferredSize(new java.awt.Dimension(166, 100));

        logArea.setColumns(20);
        logArea.setFont(new java.awt.Font("Noto Mono", 0, 10)); // NOI18N
        logArea.setRows(5);
        logArea.setEnabled(false);
        logScroll.setViewportView(logArea);

        vertSplit.setBottomComponent(logScroll);

        fileMenu.setText("File");
        menubar.add(fileMenu);

        setJMenuBar(menubar);

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(vertSplit, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vertSplit, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (final javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (final ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextconvJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (final InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextconvJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (final IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextconvJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (final javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextconvJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TextconvJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextArea logArea;
    private javax.swing.JScrollPane logScroll;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JTextArea textIn;
    private javax.swing.JScrollPane textInScroll;
    private javax.swing.JTextArea textOut;
    private javax.swing.JScrollPane textOutScroll;
    private javax.swing.JSplitPane textSplit;
    private javax.swing.JToolBar toolbar;
    private javax.swing.JSplitPane vertSplit;
    // End of variables declaration//GEN-END:variables

    javax.swing.JTextArea textIn(){return textIn;}
    javax.swing.JTextArea textOut(){return textOut;}
}
